package Presentacion;

import Negocios.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

public class panelLugar extends javax.swing.JPanel {
    clsLugar objLugar = new clsLugar();
    ArrayList<clsLugar> lugares = objLugar.ListarLugares();
    final Class[] tiposColumnasLugar = new Class[]{
            java.lang.String.class,           
            JButton.class,
            JButton.class
        };
    String[] columnasLugar = new String[]{
            "Nombre",
            "",
            ""};
    public panelLugar() {
        initComponents();
        listar();
        tbLugares.setDefaultRenderer(JButton.class, new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable jtable, Object objeto, boolean estaSeleccionado, boolean tieneElFoco, int fila, int columna) {
                return (Component) objeto;
            }
        });

        tbLugares.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tbLugares.rowAtPoint(e.getPoint());
                int columna = tbLugares.columnAtPoint(e.getPoint());
                //PARA MODIFICAR
                if (tbLugares.getModel().getColumnClass(columna).equals(JButton.class) && tbLugares.columnAtPoint(e.getPoint())==1) {
                    if (JOptionPane.showConfirmDialog(null, "Seguro que desea modificar el Lugar seleccionado?","Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==0) {
                        objLugar.setId(lugares.get(fila).getId());
                        objLugar.setNombre(lugares.get(fila).getNombre());
                        frmModificarLugar frmLugar = new frmModificarLugar(objLugar);
                        frmLugar.setVisible(true);
                    }
                }
                //PARA ELIMINAR
                if (tbLugares.getModel().getColumnClass(columna).equals(JButton.class) && tbLugares.columnAtPoint(e.getPoint())==2) {
                    if (JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el Lugar seleccionado?","Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==0) {
                        objLugar.setId(lugares.get(fila).getId());
                        if (objLugar.EliminarLugar(objLugar)) {
                            JOptionPane.showMessageDialog(null, "Lugar eliminado exitosamente");
                            listar();
                        } else {
                            JOptionPane.showMessageDialog(null, "No se pudo eliminar el Lugar");
                        }
                    }
                }
            }
        });
    }
    
    public void listar(){
        tbLugares.removeAll();
        lugares = objLugar.ListarLugares();
        Object[][] lugar = new Object[lugares.size()][3];
        int j = 0;
        for (int i = 0; i < lugares.size(); i++) {
            lugar[j][0] = lugares.get(i).getNombre();            
            lugar[j][1] = frmMain.btnEditar;
            lugar[j][2] = frmMain.btnEliminar;
            j++;
        }
        tbLugares.setModel(new javax.swing.table.DefaultTableModel(
                lugar,
                columnasLugar) {
            Class[] tipos = tiposColumnasLugar;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tbLugares.setRowHeight(45);       
        tbLugares.getColumnModel().getColumn(1).setMaxWidth(50);
        tbLugares.getColumnModel().getColumn(2).setMaxWidth(50);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevoLugar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLugares = new javax.swing.JTable();

        panel.setBackground(new java.awt.Color(236, 240, 245));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Lugares");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 153, 255));
        panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 1300, 10));

        btnNuevoLugar.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoLugar.setForeground(new java.awt.Color(51, 51, 51));
        btnNuevoLugar.setText("Nuevo Lugar");
        btnNuevoLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLugarActionPerformed(evt);
            }
        });
        panel.add(btnNuevoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 50));

        tbLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbLugares);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 530, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLugarActionPerformed
       frmAgregarLugar frmAgregar = new frmAgregarLugar();
       frmAgregar.setVisible(true);
    }//GEN-LAST:event_btnNuevoLugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoLugar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbLugares;
    // End of variables declaration//GEN-END:variables
}
