package Presentacion;

import Negocios.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

public class panelPregunta extends javax.swing.JPanel {
    clsPregunta objPregunta = new clsPregunta();
    ArrayList<clsPregunta> preguntas = objPregunta.ListarPreguntas();
    final Class[] tiposColumnasLugar = new Class[]{
            java.lang.String.class,           
            JButton.class,
            JButton.class
        };
    String[] columnasLugar = new String[]{
            "Pregunta",
            "",
            ""};
    public panelPregunta() {
        initComponents();
        listar();
        tbPreguntas.setDefaultRenderer(JButton.class, new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable jtable, Object objeto, boolean estaSeleccionado, boolean tieneElFoco, int fila, int columna) {
                return (Component) objeto;
            }
        });

        tbPreguntas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tbPreguntas.rowAtPoint(e.getPoint());
                int columna = tbPreguntas.columnAtPoint(e.getPoint());
                //PARA MODIFICAR
                if (tbPreguntas.getModel().getColumnClass(columna).equals(JButton.class) && tbPreguntas.columnAtPoint(e.getPoint())==1) {
                    if (JOptionPane.showConfirmDialog(null, "Seguro que desea modificar la Pregunta seleccionada?","Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==0) {
                        objPregunta.setId(preguntas.get(fila).getId());
                        objPregunta.setDescripcion(preguntas.get(fila).getDescripcion());
                        frmModificarPregunta frmPregunta = new frmModificarPregunta(objPregunta);
                        frmPregunta.setVisible(true);
                    }
                }
                //PARA ELIMINAR
                if (tbPreguntas.getModel().getColumnClass(columna).equals(JButton.class) && tbPreguntas.columnAtPoint(e.getPoint())==2) {
                    if (JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar la Pregunta seleccionada?","Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==0) {
                        objPregunta.setId(preguntas.get(fila).getId());
                        if (objPregunta.EliminarPregunta(objPregunta)) {
                            JOptionPane.showMessageDialog(null, "Pregunta eliminada exitosamente");
                            listar();
                        } else {
                            JOptionPane.showMessageDialog(null, "No se pudo eliminar la Pregunta");
                        }
                    }
                }
            }
        });
    }

    public void listar(){
        tbPreguntas.removeAll();
        preguntas = objPregunta.ListarPreguntas();
        Object[][] pregunta = new Object[preguntas.size()][4];
        int j = 0;
        for (int i = 0; i < preguntas.size(); i++) {
            pregunta[j][0] = preguntas.get(i).getDescripcion();            
            pregunta[j][1] = frmMain.btnEditar;
            pregunta[j][2] = frmMain.btnEliminar;
            j++;
        }
        tbPreguntas.setModel(new javax.swing.table.DefaultTableModel(
                pregunta,
                columnasLugar) {
            Class[] tipos = tiposColumnasLugar;

            @Override
            public Class getColumnClass(int columnIndex) {
                return tipos[columnIndex];
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tbPreguntas.setRowHeight(45);       
        tbPreguntas.getColumnModel().getColumn(1).setMaxWidth(50);
        tbPreguntas.getColumnModel().getColumn(2).setMaxWidth(50);
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevoLugar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPreguntas = new javax.swing.JTable();

        panel.setBackground(new java.awt.Color(236, 240, 245));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("Preguntas");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 153, 255));
        panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1300, -1));

        btnNuevoLugar.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoLugar.setForeground(new java.awt.Color(51, 51, 51));
        btnNuevoLugar.setText("Nueva Pregunta");
        btnNuevoLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLugarActionPerformed(evt);
            }
        });
        panel.add(btnNuevoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 50));

        tbPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbPreguntas);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 610, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLugarActionPerformed
       frmAgregarPregunta frmAgregar = new frmAgregarPregunta();
       frmAgregar.setVisible(true);
    }//GEN-LAST:event_btnNuevoLugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoLugar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbPreguntas;
    // End of variables declaration//GEN-END:variables
}